### ISSUE TITLE
Can't receive any message

### ISSUE THREAD

**Issue by noais** [bitrise-io/steps-slack-message#18]
I get this log message: 
`Slack message successfully sent! 🚀
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | slack@2.5.0                                                   | 5.78 sec |
+---+---------------------------------------------------------------+----------+
`

but I don't receive any message, how can I see all logs to try to find the error. My version slack is 2.6.2 this could be a problem?

**Comment by viktorbenei** [comment]
Hi @noais ,

Can you please include the whole log of the Slack step? From the step's header to its footer

**Comment by noais** [comment]
`
+------------------------------------------------------------------------------+
| (9) slack@2.5.0                                                              |
+------------------------------------------------------------------------------+
| id: slack                                                                    |
| version: 2.5.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-06-22T06:46:05-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
[34mINFO[0m[06:46:05]  * [32;1m[OK][0m Step dependency (go) installed, available. 

[34;1mSlack configs:[0m
 - WebhookURL: https://XXXXXXX.slack.com/messages/XXXXXXXXXX
 - Channel:  @everyone
 - FromUsername: Bitrise CI - OK
 - FromUsernameOnError: Bitrise CI - ERROR
 - Message: Type your message here
 - MessageOnError: 
 - Color: good
 - ColorOnError: danger
 - ImageURL: 
 - ImageURLOnError: 
 - Emoji: :white_check_mark:
 - EmojiOnError: :no_entry_sign:
 - IconURL: 
 - IconURLOnError: 

[34;1mOther configs:[0m
 - IsDebugMode: false
 - IsBuildFailed: false


[32;1mSlack message successfully sent! 🚀[0m

|                                                                              |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mslack@2.5.0[0m                                                   | 4.78 sec |
+---+---------------------------------------------------------------+----------+


+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mactivate-ssh-key@3.1.1[0m                                        | 2.31 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mgit-clone@3.4.4[0m                                               | 9.11 sec |
+---+---------------------------------------------------------------+----------+
| [33;1m![0m | [33;1mcache-pull@1.0.0 (exit code: 1)[0m                               | 3.46 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-pull/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-pull.git              |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mDo anything with Script step[0m                                  | 2.32 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mcertificate-and-profile-installer@1.8.6[0m                       | 4.73 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mrecreate-user-schemes@1.0.1[0m                                   | 7.51 sec |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mxcode-test@1.18.5[0m                                             | 151 sec  |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mdeploy-to-bitrise-io@1.3.4[0m                                    | 7.18 sec |
+---+---------------------------------------------------------------+----------+
| [33;1m![0m | [33;1mcache-push@1.1.0 (exit code: 1)[0m                               | 4.04 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-cache-push/issues    |
| Source: https://github.com/bitrise-steplib/steps-cache-push.git              |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mslack@2.5.0[0m                                                   | 4.78 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 196 sec                                                       |
+------------------------------------------------------------------------------+
`

**Comment by viktorbenei** [comment]
You should change the channel I think from `@everyone` to the name of the channel you want to send the message to, usually `#general` or `a-private-channel`

Strange that Slack accepts this web API call with the `@everyone` as the channel - if Slack would return any error this step would fail + print that.

**Comment by viktorbenei** [comment]
Or just leave the channel input empty, in that case the message will go into the channel which you selected for the webhook on Slack

**Comment by noais** [comment]
look [this](http://imgur.com/jUY9xFT) configuration, my output log still have: 
>Channel: @everyone

**Comment by viktorbenei** [comment]
Are you sure that you changed this in the workflow you run? Might be that you changed it in another workflow.

**Comment by noais** [comment]
I'm sure. I verify twice, I remove the workflow and create again. I have only this workflow create so I'm sure this is the one.

**Comment by viktorbenei** [comment]
Can you please send us the build's Bitrise.io url through email or the onsite chat?

**Comment by noais** [comment]
yes I can, please explain me how I can do this?

**Comment by viktorbenei** [comment]
If you're OK with that you can copy paste the build's URL here too (just open the build's page on bitrise.io and copy paste the URL), or send an email https://www.bitrise.io/contact

**Comment by noais** [comment]
done

**Comment by viktorbenei** [comment]
Checked the log, and in that build you ran the `primary` workflow, and checking the related build config (`bitrise.yml` in the editor):

```
  primary:
    steps:
...
    - cache-push@1.1.0: {}
    - slack@2.5.0:
        inputs:
        - webhook_url: REDACTED
        - channel: " @everyone"
```

So in this build (the one you sent me) this was indeed set to `@everyone`.

If you changed the config since, that will only be applied on new builds not on previously finished ones. Also make sure that if you change the config you Save the workflow/config (top right corner in the editor) and start a new build, that will use the updated config.

**Comment by noais** [comment]
I remove '#general' on `Target Slack channel, group or username` the field is empty now.
After building `- channel: " @everyone"` still there.

**Comment by viktorbenei** [comment]
Can you please remove it in the yml directly? Might be an editor issue. Editing the yml directly should definitely work.

**Comment by noais** [comment]
Now is correct: 
The Chanel is right, but still didn't work. I didn't receive the message on slack.

**Comment by viktorbenei** [comment]
Can you please send the new build's url?

**Comment by noais** [comment]
Done

**Comment by viktorbenei** [comment]
Two things:

1. Is this a private channel? If it is, I believe it have to be specified without the `#` prefix
1. More likely, I think the webhook URL you specified is wrong. You need an **Incoming WebHooks** webhook, which looks like `https://hooks.slack.com/services/X/Y/Z`. Yours look like `https://X.slack.com/messages/Y`

I believe this is most likely `#2`, not sure what kind of Slack hook URL the `/messages/` one is, but doesn't seem like an Incoming WebHook one.

One more note which might help debugging: enable the **Debug mode?** option of this step (`is_debug_mode`) which will print the response from Slack.

I also scheduled an improvement for this (https://github.com/bitrise-io/steps-slack-message/issues/19) as the step right now only checks the http status code of the response, and not the response body. In case if the Incoming WebHook param is OK that is enough, but if that is not an Incoming WebHook then the other server/endpoint might still respond with a 200 (OK) http code, even though that won't process the message.

**Comment by viktorbenei** [comment]
About how you can register an Incoming WebHook URL on Slack please check the step's description on the UI, or here in the YML definition: https://github.com/bitrise-io/steps-slack-message/blob/master/step.yml#L4

**Comment by noais** [comment]
I realise the webhook  I configure on the workflow isn't different of the yml. I change directly on the yml all my settings and works. The conclusion I had is the UI isn't writing well the yml file.
Tks for the help!

**Comment by viktorbenei** [comment]
Any time ;)

P.S.: I scheduled some debugging time for myself today to try to reproduce this issue in the editor and schedule a fix if we can reproduce the behaviour

**Comment by noais** [comment]
I used Safari(10.1.1) on macOS Sierra.

**Comment by viktorbenei** [comment]
Hmm.. Are you sure that you did click "Save" at the top right corner @noais ?

I tried to reproduce it, with Safari (Version 10.1.1 (12603.2.4)) on macOS Sierra (10.12.5 (16F73)) but it worked for me, both on bitrise.io and from the CLI, using the Slack step, changing the webhook & channel inputs.

If you're sure you did click "Save" after changing these params in the editor, do you have any idea what might cause this issue? Did you do anything else in the editor?

Also, if that's not too much to ask, could you enable "Support Account" Access on the Settings tab of your app, so that we can check the editor with our support account? Maybe it's something related to your config.. Not sure as no matter what I tried it worked for me every time :/

**Comment by noais** [comment]
I have it enable. 

I verify now everything I do doesn't write on the yml file, changing workflows orders, configuration of the workflows and now you are telling me to enable support where I already have enable. 

Yes I save the changes all the time (sometimes by keyboard cmd+s), is my first time trying bitrise maybe I have done something wrong but I can't help you more.

**Comment by noais** [comment]
feel free to ask me all things you want 👍

**Comment by viktorbenei** [comment]
We'll check it with the support account asap! 

Can you try it from another browser? Does it happen there too?

**Comment by noais** [comment]
I found this:
```
workflows:
  deploy:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.4.4: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.8.6: {}
    - recreate-user-schemes@1.0.1:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - xcode-test@1.18.5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - xcode-archive@2.0.6:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - deploy-to-bitrise-io@1.3.5: {}
    - cache-push@1.1.0: {}
    - slack:
        inputs:
        - webhook_url: https://hooks.slack.com/services/xxxxx/yyyy/zzzz
        - message: 'FirstBolck:'
        - image_url: https://media.giphy.com/media/2cmCUDzzxscnK/giphy.gif
        - image_url_on_error: https://media.giphy.com/media/R5bMadwZdTrri/giphy.gif
  primary:
    steps:
    - activate-ssh-key@3.1.1:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@3.4.4: {}
    - cache-pull@1.0.0: {}
    - script@1.1.4:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.8.6: {}
    - recreate-user-schemes@1.0.1:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
    - xcode-test@1.18.5:
        inputs:
        - project_path: "$BITRISE_PROJECT_PATH"
        - scheme: "$BITRISE_SCHEME"
    - deploy-to-bitrise-io@1.3.4: {}
    - cache-push@1.1.0: {}
    - slack@2.5.0:
        inputs:
        - webhook_url: https://hooks.slack.com/services/xxx/yyy
        - channel: "#General"
        - message: 'Result:'
        - image_url_on_error: https://media.giphy.com/media/R5bMadwZdTrri/giphy.gif
        - image_url: https://media.giphy.com/media/2cmCUDzzxscnK/giphy.gif`
```
When I change something on the UI this changes are made on the slack first block (where  - message: is 'FirstBolck:'), but when I build the app the configurations use are the second block. This makes any sense to you?
