### ISSUE TITLE
Improvement: Allow sub environnement variable in message

### ISSUE THREAD

**Issue by odemolliens** [bitrise-io/steps-slack-message#21]
That would be really great to manage environnement variable in environnement variable for the message part.

For a better explanation, imagine: 

Workflow name: `123`

```
app:
  envs:
  - SLACK_MSG_START_WORKFLOW: '==== \n Start Workflow: $BITRISE_TRIGGERED_WORKFLOW_TITLE
      \n ===='
    opts:
      is_expand: false
```

```
  steps:
    - slack:
        title: Start Workflow
        inputs:
        - message: '$SLACK_MSG_START_WORKFLOW'
```

Actual version of the plugin display on Slack:
```
====
Start Workflow: $BITRISE_TRIGGERED_WORKFLOW_TITLE :rotating_light:  
====
```
Instead of 

```
====
Start Workflow: 123 :rotating_light:  
====
```
