### ISSUE TITLE
Slack threads error when using projects slack integration

### ISSUE THREAD

**Issue by vortexture** [bitrise-io/steps-slack-message#96]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.2.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? UNKNOWN

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description
I am trying to set up slack threads for my build messages, I have followed this guide https://devcenter.bitrise.io/en/workspaces/workspace-slack-integration.html to setup the intergration, then in my "Send a Slack message" step I am setting the integration Id and trying to export the env var `BUILD_STARTED_MESSAGE_ID` for the "The newly created thread timestamp environment variable name" configuration, but I keep getting the error "failed to export outputs: For output support, do not submit a WebHook URL"

Here is my input
```
Input:

- Debug: true
- BuildAPIToken: *****
- BuildURL: https://app.bitrise.io/build/XXXX
- WebhookURL: 
- WebhookURLOnError: 
- APIToken: 
- IntegrationID: [REDACTED]
- IntegrationIDOnError: 
- Channel: 
- ChannelOnError: 
- Text: 
- TextOnError: 
- IconEmoji: 
- IconEmojiOnError: 
- IconURL: https://github.com/bitrise-io.png
- IconURLOnError: https://github.com/bitrise-io.png
- LinkNames: true
- Username: Bitrise
- UsernameOnError: Bitrise
- ThreadTs: 
- ThreadTsOnError: 
- Ts: 
- TsOnError: 
- ReplyBroadcast: false
- ReplyBroadcastOnError: false
- Color: #37C5F0
- ColorOnError: #f0741f
- PreText: *Build Starting* - 📱 Deploy App
- PreTextOnError: *Build Failed!*
- AuthorName: 
- Title: 
- TitleOnError: 
- TitleLink: 
- Message: 
- MessageOnError: 
- ImageURL: 
- ImageURLOnError: 
- ThumbURL: 
- ThumbURLOnError: 
- Footer: Bitrise
- FooterOnError: Bitrise
- FooterIcon: https://github.com/bitrise-io.png?size=16
- FooterIconOnError: https://github.com/bitrise-io.png?size=16
- TimeStamp: true
- Fields: App
Branch|XXX
Pipeline|pipeline-name
Workflow|workflow-name

- Buttons: View App|https://app.bitrise.io/app/XXXX
View Pipeline Build|https://app.bitrise.io/app/XXXX/pipelines/XXXX
View Workflow Build|https://app.bitrise.io/build/XXXX

- BuildStatus: 0
- PipelineBuildStatus: succeeded
- ThreadTsOutputVariableName: BUILD_STARTED_MESSAGE_ID
Error: failed to export outputs: For output support, do not submit a WebHook URL
```

This is the yaml for the steps current configuration
```yml
  notify-pipeline-started:
    steps:
    - slack@4:
        inputs:
        - pretext: "*Build Starting* - $BITRISE_GIT_MESSAGE ($BITRISE_BUILD_NUMBER)"
        - buttons: |
            View App|${BITRISE_APP_URL}
            View Pipeline Build|${BITRISEIO_PIPELINE_BUILD_URL}
            View Workflow Build|${BITRISE_BUILD_URL}
        - color: "#37C5F0"
        - output_thread_ts: BUILD_STARTED_MESSAGE_ID
        - workspace_slack_integration_id: "$SLACK_INTERGRATION_ID"
        - is_debug_mode: 'yes'
```

Any ideas what's going wrong? Am I configuring this incorrectly?

### Bitrise info

- Build URL: https://app.bitrise.io/build/36fd0e57-3a5f-4b13-b0ef-1ecb55d4a7d8
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
[DEBUG] GET https://app.bitrise.io/build/[REDACTED]/integrations/slack/[REDACTED]
Request to Slack: [REDACTED]

Error: failed to export outputs: For output support, do not submit a WebHook URL
Error: failed to export outputs: For output support, do not submit a WebHook URL
  </pre>
</details>

### Steps to reproduce

1. Setup slack integration for project
2. Set slack integration Id from secret in "Send a Slack message" step setting called "Workspace Slack Integration ID (Integration ID, Webhook or API token is required)"
3. Set a env var name for the "The newly created thread timestamp environment variable name" option
4. Run the workflow
